hazards = {
  "traffic light": ["choking on small parts"],
  "fire hydrant": ["heavy and could cause injury if it falls"],
  "stop sign": ["sharp edges", "choking on small parts"],
  "parking meter": ["choking on small parts"],
  "bench": ["falling off"],
  "bird": ["disease transmission", "scratching", "biting"],
  "cat": ["scratching", "biting", "allergies"],
  "dog": ["biting", "knocking over", "allergies"],
  "horse": ["falling off", "being kicked or bitten"],
  "sheep": ["biting"],
  "cow": ["being kicked"],
  "elephant": ["being trampled"],
  "bear": ["biting", "mauling"],
  "zebra": ["biting", "kicking"],
  "giraffe": ["kicking"],
  "backpack": ["strangulation from straps", "choking on small parts"],
  "umbrella": ["eye injury", "choking on small parts"],
  "handbag": ["choking on small contents", "strangulation from straps"],
  "tie": ["strangulation"],
  "suitcase": ["falling onto child", "trapping inside"],
  "frisbee": ["choking on broken pieces"],
  "skis": ["sharp edges"],
  "snowboard": ["sharp edges"],
  "sports ball": ["choking on small, detachable parts"],
  "kite": ["strangulation from string"],
  "baseball bat": ["blunt force injuries"],
  "baseball glove": ["choking on small parts"],
  "skateboard": ["fall injuries"],
  "surfboard": ["falling off", "drowning"],
  "tennis racket": ["strangulation from strings", "choking on detached parts"],
  "bottle": ["choking on cap", "shattering"],
  "wine glass": ["shattering and causing cuts"],
  "cup": ["choking on broken pieces"],
  "fork": ["puncture wounds"],
  "knife": ["cuts"],
  "spoon": ["choking on small, detachable parts"],
  "bowl": ["choking on broken pieces"],
  "banana": ["choking on small pieces"],
  "apple": ["choking on small pieces"],
  "sandwich": ["choking on large pieces"],
  "orange": ["choking on small pieces"],
  "broccoli": ["choking on small pieces"],
  "carrot": ["choking on small pieces"],
  "hot dog": ["choking on whole or large pieces"],
  "pizza": ["choking on large pieces"],
  "donut": ["choking on small pieces"],
  "cake": ["choking on small pieces"],
  "chair": ["falling off"],
  "sofa": ["suffocation from getting trapped between cushions"],
  "pottedplant": ["choking on small parts", "toxicity from some plants"],
  "bed": ["suffocation", "falling off"],
  "diningtable": ["falling off", "sharp edges"],
  "toilet": ["drowning"],
  "tvmonitor": ["falling onto child"],
  "laptop": ["electrical shock", "heavy and could cause injury"],
  "mouse": ["choking on small parts"],
  "remote": ["choking on batteries", "electrical shock"],
  "keyboard": ["choking on keys"],
  "cell phone": ["choking on small parts", "electrical shock"],
  "microwave": ["burns"],
  "oven": ["burns"],
  "toaster": ["electrical shock", "burns"],
  "sink": ["drowning"],
  "refrigerator": ["trapping inside", "falling onto child"],
  "book": ["paper cuts", "choking on small, torn pieces"],
  "clock": ["choking on small parts", "falling onto child"],
  "vase": ["shattering and causing cuts"],
  "scissors": ["cuts"],
  "teddy bear": ["choking on small parts", "suffocation if large enough"],
  "hair drier": ["electrical shock", "burns"],
  "toothbrush": ["choking"]
}

test = {
    "frisbee": ["Choking Hazard"],
    "baseball bat": ["Choking Hazard"],
    "baseball glove": ["Choking Hazard"],
    "skateboard": ["Choking Hazard"],
    "surfboard": ["Choking Hazard"],
    "tennis racket": ["Choking Hazard"],
    "bottle": ["Choking Hazard"],
    "wine glass": ["Choking Hazard", "Breaking Hazard"],
    "cup": ["Choking Hazard"],
    "fork": ["Choking Hazard"],
    "knife": ["Choking Hazard", "Cutting or Puncture Hazard"],
    "spoon": ["Choking Hazard"],
    "bowl": ["Choking Hazard"],
    "banana": ["Choking Hazard"],
    "apple": ["Choking Hazard"],
    "sandwich": ["Choking Hazard"],
    "orange": ["Choking Hazard"],
    "broccoli": ["Choking Hazard"],
    "carrot": ["Choking Hazard"],
    "Hot dog": ["Choking Hazard"],
    "Pizza": ["Choking Hazard"],
    "Donut": ["Choking Hazard"],
    "Cake": ["Choking Hazard"],
    "Remote": ["Choking Hazard"],
    "Cell phone": ["Choking Hazard", "Electrocution Hazard"],
    "Mouse": ["Choking Hazard"],
    "Scissors": ["Choking Hazard", "Cutting or Puncture Hazard"],
    "Teddy bear": ["Choking Hazard"],
    "Toothbrush": ["Choking Hazard", "Poisoning/Choking Hazard"],
    "Chair": ["Crushing Hazard"],
    "Sofa": ["Crushing Hazard"],
    "Bed": ["Crushing Hazard"],
    "Dining table": ["Crushing Hazard"],
    "TV monitor": ["Crushing Hazard", "Electrocution Hazard"],
    "Laptop": ["Crushing Hazard", "Electrocution Hazard"],
    "Microwave": ["Electrocution Hazard", "Burn Hazard"],
    "Oven": ["Electrocution Hazard", "Burn Hazard"],
    "Toaster": ["Electrocution Hazard", "Burn Hazard"],
    "Hair drier": ["Electrocution Hazard", "Poisoning/Choking Hazard"],
    "Vase": ["Breaking Hazard"],
    "Bicycle": ["Risk of Injury"],
    "Car": ["Risk of Injury"],
    "Motorbike": ["Risk of Injury"],
    "Aeroplane": ["Risk of Injury"],
    "Bus": ["Risk of Injury"],
    "Train": ["Risk of Injury"],
    "Truck": ["Risk of Injury"],
    "Boat": ["Risk of Injury"],
    "Traffic light": ["Other Hazards"],
    "Fire hydrant": ["Other Hazards"],
    "Stop sign": ["Other Hazards"],
    "Parking meter": ["Other Hazards"],
    "Bench": ["Other Hazards"],
    "Umbrella": ["Other Hazards"],
    "Handbag": ["Other Hazards"],
    "Tie": ["Other Hazards"],
    "Suitcase": ["Other Hazards"],
    "Potted plant": ["Other Hazards"],
    "Book": ["Other Hazards"],
    "Clock": ["Other Hazards"]
}
